### ISSUE TITLE
Add enstil.ai

### ISSUE THREAD

**Issue by usernamex** [altryne/awesome-ai-art-image-synthesis#9]
**Why is it awesome?**
It is unlimited and free and you can find prompt inspiration by searching other prompts with output generated.

** Link **
[Add a link](http://enstil.ai/)

**Screenshot / Twitter thread raving about this**
<img width="697" alt="image" src="https://user-images.githubusercontent.com/221655/188102551-b8b14917-7516-44ac-bfcd-c80c7d629d8f.png">

**Comment by altryne** [comment]
Thanks for the suggestion, it didn't work for me when I tried it, I'll revisit in a month

**Comment by usernamex** [comment]
Yes, it was down, but it working again.
